version: '3'
services:
  mininet:
    image: iwaseyusuke/mininet:ubuntu-22.04  #latest
    tty: true
    network_mode: "host"
    privileged: true
    working_dir: /APP/workflow-volume
    entrypoint: ./entrypoint/mininetBash.sh
    environment:
     - DISPLAY
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
     - $PWD/workflow-volume:/APP/workflow-volume
    
  
  wireshark:
    image: linuxserver/wireshark:latest
    working_dir: /APP/workflow-volume
    entrypoint: python entrypoint/wireshark.py
    volumes:
      - $PWD/workflow-volume:/APP/workflow-volume
    depends_on:
      mininet:
        condition: service_completed_successfully


  cicflowmeter_attack:
    image: mielverkerken/cicflowmeter:latest
    volumes:
      - $PWD/workflow-volume:/tmp/pcap
    command: ["/tmp/pcap/cicflowmeter/attack_output_ordered", "/tmp/pcap/cicflowmeter/attack_output"]
    depends_on:
      wireshark:
        condition: service_completed_successfully

  cicflowmeter_benign:
    image: mielverkerken/cicflowmeter:latest
    volumes:
      - $PWD/workflow-volume:/tmp/pcap
    command: ["/tmp/pcap/cicflowmeter/benign_output_ordered", "/tmp/pcap/cicflowmeter/benign_output"]
    depends_on:
      cicflowmeter_attack:
        condition: service_completed_successfully

  scikit:
    image: quay.io/jupyter/datascience-notebook:2024-03-14
    volumes:
      - $PWD/workflow-volume:/APP/workflow-volume
    working_dir: /APP/workflow-volume
    user: root
    entrypoint: ./entrypoint/scikitBash.sh
    depends_on:
      cicflowmeter_benign:
        condition: service_completed_successfully