version: '3'
services:
  mininet:
    build:
      context: .
      dockerfile: Dockerfile_mininet
    image: iwaseyusuke/mininet:ubuntu-22.04  #latest
    tty: true
    network_mode: "bridge"
    privileged: true
    environment:
     - DISPLAY
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
     - $PWD/workflow-volume:/APP/workflow-volume
    
  
  wireshark:
    build: 
      context: .
      dockerfile: Dockerfile_wireshark
    image: alexandreoda/wireshark:latest
    volumes:
      - $PWD/workflow-volume:/APP/workflow-volume
    depends_on:
      mininet:
        condition: service_completed_successfully


  cicflowmeter:
    image: mielverkerken/cicflowmeter:latest
    volumes:
      - $PWD/workflow-volume:/tmp/pcap
    command: ["/tmp/pcap/input", "/tmp/pcap/output"]
    depends_on:
      wireshark:
        condition: service_completed_successfully

  scikit:
    image: devashishupadhyay/scikit-learn-docker:latest
    volumes:
      - $PWD/workflow-volume:/APP/workflow-volume